// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzUGpsW5TrHGebv3E_pGttsWy_kFCl6Ho',
    appId: '1:802878070287:web:5ba82838319a4b88b74d7a',
    messagingSenderId: '802878070287',
    projectId: 'chulesi-fooddelivery',
    authDomain: 'chulesi-fooddelivery.firebaseapp.com',
    storageBucket: 'chulesi-fooddelivery.appspot.com',
    measurementId: 'G-KGT7XRYQEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-x4SPWIhWbpTQAMlu52qvdmDclE_egHU',
    appId: '1:802878070287:android:895024f7c60960edb74d7a',
    messagingSenderId: '802878070287',
    projectId: 'chulesi-fooddelivery',
    storageBucket: 'chulesi-fooddelivery.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChrFY3BSFFetUIoenQ5zvTA5hUCDrl4N8',
    appId: '1:802878070287:ios:8d17d98f8a960254b74d7a',
    messagingSenderId: '802878070287',
    projectId: 'chulesi-fooddelivery',
    storageBucket: 'chulesi-fooddelivery.appspot.com',
    iosBundleId: 'com.example.frontend',
  );
}
